# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::212224127201:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-IE3Y2s4giydx
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::212224127201:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-11T03:07:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1359"
  uid: 5c959961-cdb8-4776-8128-d0c8a32b8314
